// ai-tutor.js (옵션 1 - 완전판)
/**
 * AI Tutor Configuration
 * Used by: server.js /api/chat endpoint for live student conversations
 * 
 * IMPORTANT: The actual system prompt is generated by Step 4 and stored in the database.
 * This file only provides the OpenAI API configuration parameters.
 */

export const config = {
    model: "gpt-4o",           // Fast, cost-effective for conversational AI
    temperature: 0.7,          // Balanced: natural but consistent responses
    max_tokens: 500,           // Keep responses short (A2-B1 appropriate)
    presence_penalty: 0.3,     // Reduce repetitive phrases
    frequency_penalty: 0.3     // Encourage vocabulary diversity
};

// Legacy function - not currently used in the application
// Kept for backward compatibility
export function generateSystemPrompt(aiScaffoldingPrompt) {
    return aiScaffoldingPrompt;
}